export const ROUTES = {
  home: "/",
  pricing: "/pricing",
  signIn: "/sign-in",
  signUp: "/sign-up",
  docs: "/docs",
  termsAndConditions: "/terms-conditions",
  dashboard: "/dashboard",
  dashboardAdmin: {
    users: "/dashboard/users",
    organizations: "/dashboard/organizations",
    settings: "/dashboard/settings",
    subscriptions: "/dashboard/subscriptions",
    salesInquiries: "/dashboard/sales-inquiries",
    salesInquiriesStats: "/dashboard/sales-stats",
    systemLogs: "/dashboard/system-logs",
    revenueAnalysis: "/dashboard/revenue-analysis",
    creditTransaction: "/dashboard/credit-transactions",
    

  },
  dashboardOrgAdmin: {
    bookingManagement: "/dashboard/booking-management",
    bookingStats: "/dashboard/booking-stats",
    resourcesManagement: "/dashboard/resources-management",
    staffManagement: "/dashboard/staff-management",
    creditManagement: "/dashboard/credit-management",
    billing: "/dashboard/billing",
  },
  dashboardStaff: {
    // requestSupport: "/dashboard/request-support",
  },
  dashboardCommon: {
     staffOverview: "/dashboard/staff-overview",
     overview: "/dashboard/overview",
    bookingAvailability: "/dashboard/booking-availability",
    bookings: "/dashboard/bookings-calendar",
    myBookings: "/dashboard/my-bookings",
    resources: "/dashboard/resources",
    profile: "/dashboard/profile",
    community: "/dashboard/community",
    myPosts: "/dashboard/community/my-posts",
    notifications: "/dashboard/notifications",
  },
} as const;
