"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _resources_main from './resources-main.bones.json'

registerBones({
  "resources-main": _resources_main,
})
